name: ci
on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:13f9b8cc2f901e98c253595c4070254ece08543f6e100b4fa6682f87de4388eb
    steps:
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile && yarn fmt
  lint:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:13f9b8cc2f901e98c253595c4070254ece08543f6e100b4fa6682f87de4388eb
    steps:
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile && yarn lint
  test:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:13f9b8cc2f901e98c253595c4070254ece08543f6e100b4fa6682f87de4388eb
    steps:
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile && yarn test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage.html
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: ci/out/coverage.html
