name: ci
on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:046cd02e79dcbf81dc06eb6fd333fa8643f2503f437ddd46a4c1af9132078a2c
    steps:
      - uses: actions/checkout@v1
      - run: make fmt
  lint:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:046cd02e79dcbf81dc06eb6fd333fa8643f2503f437ddd46a4c1af9132078a2c
    steps:
      - uses: actions/checkout@v1
      - run: make lint
  test:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:046cd02e79dcbf81dc06eb6fd333fa8643f2503f437ddd46a4c1af9132078a2c
    steps:
      - uses: actions/checkout@v1
      - run: make test
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      - name: Upload coverage.html
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: ci/out/coverage.html
