name: ci
on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:54a12b52be98d2d1588a054cfce35d17705c9b45546478d8bcdbac2a89a90001
    steps:
      - uses: actions/checkout@v1
      - run: make fmt
  lint:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:54a12b52be98d2d1588a054cfce35d17705c9b45546478d8bcdbac2a89a90001
    steps:
      - uses: actions/checkout@v1
      - run: make lint
  test:
    runs-on: ubuntu-latest
    container: nhooyr/websocket-ci@sha256:54a12b52be98d2d1588a054cfce35d17705c9b45546478d8bcdbac2a89a90001
    steps:
      - uses: actions/checkout@v1
      - run: make test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage.html
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: ci/out/coverage.html
